name: "Install Rust"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      name: Install Python $PYTHON_VERSION_INSTALL
      with:
        python-version: $PYTHON_VERSION_INSTALL
    - run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL https://sh.rustup.rs | sh -s -- --default-toolchain none -y
          source $HOME/.cargo/env
          rustup toolchain install stable --profile minimal --no-self-update 
          rustup default stable
          rustup target add x86_64-unknown-linux-gnu --toolchain stable
          rustup target add aarch64-unknown-linux-gnu --toolchain stable
          pip install cargo-lambda==$PIP_CARGO_LAMBDA_VERSION
      name: Install Rust and cargo-lambda pip package
      shell: bash