version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7

    commands:
      - pip install --upgrade pip aws-sam-cli
      - pip install -r requirements.txt
      - ruby --version

  post_build:
    commands:
      - sam --version
      - pytest -vvv tests/integration/unit_test/test_unit_test_ruby2_7.py -n 4
