version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip aws-sam-cli
      - pip install -r requirements.txt
      # Install rustup
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      # Configure cargo for the current shell
      - source $HOME/.cargo/env
      # Install cross for cross-compilation
      - cargo install cross
  
  post_build:
    commands:
      - sam --version
      # sam build doesn't support building Rust Lambda functions
      # - pytest -vvv tests/integration/build_invoke/test_build_invoke_rust.py -n 4
      - pytest -vvv tests/integration/unit_test/test_unit_test_rust.py -n 4