version: 0.2

phases:
  install:
    commands:
      # install dotnet 6.0 since the runtime is not provided
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash -s -- --channel LTS

      # install test requirements
      - pip install --upgrade pip aws-sam-cli
      - pip install -r requirements.txt
      - dotnet --info

  post_build:
    commands:
      - sam --version
      - pytest -vvv tests/integration/build_invoke/test_build_invoke_dotnet6_0.py -n 4
