version: 0.2

env:
  variables:
    CARGO_LAMBDA_VERSION: "0.17.1"

phases:
  install:
    commands:
      - pip install --upgrade pip aws-sam-cli
      - pip install -r requirements.txt
      # Install rustup
      - curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL https://sh.rustup.rs | sh -s -- --default-toolchain none -y
      # Configure cargo for the current shell
      - source $HOME/.cargo/env
      - rustup toolchain install stable --profile minimal --no-self-update 
      - rustup default stable
      - rustup target add x86_64-unknown-linux-gnu --toolchain stable
      - rustup target add aarch64-unknown-linux-gnu --toolchain stable
      # Install Cargo Lambda
      - pip install cargo-lambda==$CARGO_LAMBDA_VERSION
      - rustc -V
      - cargo -V
      - cargo lambda -V
  
  post_build:
    commands:
      - sam --version
      - pytest -vvv tests/integration/build_invoke/test_build_invoke_rust.py -n 4
      - pytest -vvv tests/integration/unit_test/test_unit_test_rust.py -n 4
