version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - n 18
      - pip install --upgrade pip aws-sam-cli
      - pip install -r requirements.txt
      - node --version

  post_build:
    commands:
      - sam --version
      - pytest -vvv tests/integration/unit_test/test_unit_test_nodejs18_x.py -n 4
