version: 0.2

phases:
  install:
    commands:
      # install python 3.6 because it is not available on codebuild anymore
      - yum -y groupinstall development
      - yum -y install zlib-devel
      - wget https://www.python.org/ftp/python/3.6.12/Python-3.6.12.tar.xz
      - tar xJf Python-3.6.12.tar.xz
      - cd Python-3.6.12
      - ./configure
      - make -j4
      - make install
      - cd ..
      # upgrade sam-cli
      - pip install --upgrade aws-sam-cli
      # install pip
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python3.6 get-pip.py
      # install requirements
      - python3.6 -m pip install -r requirements.txt
      - python3.6 --version

  post_build:
    commands:
      - sam --version
      - python3.6 -m pytest -vvv tests/integration/unit_test/test_unit_test_python3_6.py -n 4
