version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1

    commands:
      - pip install --upgrade pip aws-sam-cli
      - pip install -r requirements.txt
      - dotnet --info

  post_build:
    commands:
      - sam --version
      - pytest -vvv tests/integration/build_invoke/test_build_invoke_dotnetcore3_1.py
      - pytest -vvv tests/integration/unit_test/test_unit_test_dotnetcore3_1.py -n 4
