AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  Sample SAM Template for {{ cookiecutter.project_name }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  {{cookiecutter.function_name}}:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: {{cookiecutter.function_name}}
      Handler: helloworld.App::handleRequest
      Runtime: {{ cookiecutter.runtime }}
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: CloudWatchEvent # More info about CloudWatchEvent Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent
          Properties:
            #EventBusName: your-event-bus-name #Uncomment this if your events are not on the 'default' event bus
            Pattern:
              source:
                - {{ cookiecutter.AWS_Schema_source }}
              detail-type:
                - {{ cookiecutter.AWS_Schema_detail_type }}

Outputs:
  {{cookiecutter.function_name}}:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt {{cookiecutter.function_name}}.Arn
  {{cookiecutter.function_name}}IamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt {{cookiecutter.function_name}}.Arn
