name: Build and Test Templates

on:
  pull_request:
    branches: ["master"]
  
jobs:
  run-workflow:
    name: PR Workflow
    # if: github.repository_owner == "aws"
    runs-on: ubuntu-latest
    needs:
      - build-test-python
    steps:
      - name: report-failure
        if: needs.build-test-python.result != 'success'
        run: exit 1
      - name: report-success
        run: exit 0

  build-test-python:
    name: Build and Test / Python ${{ matrix.version }}
    # if: github.repository_owner == "aws"
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "3.7"
            file: "tests/integration/unit_test/test_unit_test_python3_7.py"
          - version: "3.7"
            file: "tests/integration/unit_test/test_unit_test_python3_8.py"
          - version: "3.7"
            file: "tests/integration/unit_test/test_unit_test_python3_9.py"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout PR
      - uses: actions/aws-sam-cli-develop@v1
      - uses: actions/setup-python@v4
        name: Setup Python ${{ matrix.python }}
        with:
          python-version: ${{ matrix.python }}
      - name: Run build tests for ${{ matrix.file }}
        run: |
          pip install -r requirements.txt
          SAM_CLI_DEV=1 pytest -vvv ${{ matrix.file }} -n 4