name: "Manifest Backward Compatibility Check"
on:
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]
    branches: [master]

jobs:
  check-manifest-backward-compatibility:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run validate manifest against manifest-schema
        run: |
          pip install json-spec
          json validate --schema-file=manifest-schema.json --document-file=manifest.json
