name: "Manifest Backward Compatibility Check"
on:
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]
    branches: [master]

jobs:
  check-manifest-backward-compatibility:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run validate manifest against manifest-schema
        run: |
          pip install json-spec
          json validate --schema-file=manifest-schema.json --document-file=manifest.json
  check-manifest-schema-is-not-changed:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: Check for manifest-schema.json changes
        shell: bash
        run: |
          if git log --name-only -n 2 ${{github.sha}} | grep "manifest-schema.json"; then
            echo "Backward Incompatible change found!"
            exit 1
          fi
